name: Deploy React App
on: push 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code from GitHub
        uses: actions/checkout@v4 
      - name: Cache dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm # данный путь фиксирован для всех ubuntu-машин
          # ключ валидности хэша
          # лучше делать динамический ключ в зависимости от версий package-lock.json (где указаны версии установленных пакетов)
          # данный кэш один для всех job внутри одного WF
          key: node_modules-${{ hashFiles('**/package-lock.json') }} 
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code from GitHub
        uses: actions/checkout@v4 
      - name: Cache dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm 
          key: node_modules-${{ hashFiles('**/package-lock.json') }} 
      - name: Install dependencies
        run: npm install 
      - name: Liny application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Get source code from GitHub
        uses: actions/checkout@v4 
      - name: Cache dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm 
          key: node_modules-${{ hashFiles('**/package-lock.json') }}}} 
      - name: Install dependencies
        run: npm install 
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
  