name: Deploy React App
on: push
jobs:
  # оптимизация выполнения списка задач из файла ./deploument-steps.yml
  # с соблюдением порядка выполнения задач
  # такой подход позволяет быстрее выполнять задачи т
  # не будет постоянного получения кода и установки необходимых зависимостей
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code from GitHub
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Liny application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
