name: Print Pull Request Context
on: 
  # перечиляем events на которые реагирует наш workflow
  workflow_dispatch:
  # перечисляем activity types для pull Request
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: echo "${{ toJSON(github.event) }}"
