name: Deploy React App
on: push # сработка на push 
jobs:
  # задачи запускаются параллельно и не зависят друг от друга
  # название задачи
  test:
  # на какой машине/сервере с какой ОС запускается данный workflow 
    runs-on: ubuntu-latest
    steps:
      # название текущего шага
      - name: Get source code from GitHub
      # uses - использование workflow, который находиться на GitHub Marketplace
        uses: actions/checkout@v4 # получаем код из репозитория GitHub на наш сервер
      - name: Install dependencies
        run: npm install # ну лучше использовать npm ci - так более корректная установка идет
      - name: Run tests
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    # указали зависимость от задачи тестирования (т.е. мы запускаем задачу линтинга только если все тесты прошли успешно)
    needs: test
    steps:
      - name: Get source code from GitHub
        uses: actions/checkout@v4 
      - name: Install dependencies
        run: npm install 
      - name: Liny application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get source code from GitHub
        uses: actions/checkout@v4 
      - name: Install dependencies
        run: npm install 
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
  